const commonAddress = "http://www.crazyjt.cn"
export const API_PostSignIn = commonAddress + "/restaurant_manager/mobileLogin"
export const API_PostWorkerInfo = commonAddress + "/restaurant_manager/moblieWorkerInfo"
export const API_PostMenuList = commonAddress + "/restaurant_manager/mobileMenus"
export const API_PostTableList = commonAddress + "/restaurant_manager/mobileTables"
export const API_PostTableOperator = commonAddress + "/restaurant_manager/mobileTableOperator"
export const API_PostTableInfo = commonAddress + "/restaurant_manager/mobileTableInfo"
export const API_PostOrderInfo = commonAddress + "/restaurant_manager/mobileOrder"